spring.application.name=preparacion
server.port=8088
server.address=0.0.0.0

# Credenciales definidas previamente en el docker-compose
spring.datasource.url=jdbc:mysql://mysql_servidor2:3306/universidad_backend?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate para crear tablas automáticamente en base al código
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# En el servicio (corriendo en EC2-B), llamando al servicio (en EC2-A)
subpedido.service.url=http://18.210.19.5:8086
notificacion.service.url=http://100.52.12.161:8089
pporden.service.url=http://18.210.19.5:8085

# Habilitar SpringDoc y Swagger UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html