services:

  basedatos-mysql:
    image: mysql:8.0.33
    container_name: mysql_servidor_dockerpreparacion
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: universidad_backend
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  microservicio-pagos:
    image: misconcha/microservicio-preparacion:v1-conchah
    container_name: api_preparacion
    restart: always
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://basedatos-mysql:3306/universidad_backend
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SUBPEDIDO_URL: http://18.210.19.5:8086
      NOTIFICACION_URL: http://34.231.120.127:8083
      PPORDEN_URL: http://18.210.19.5:8085

    depends_on:
      - basedatos-mysql

volumes:
  mysql_data: